#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os.path
import wikipedia
# Parses arguments
if len(sys.argv) != 2:
    print ('Usage:', sys.argv[0], '<text file>')
    sys.exit(1)
filename = sys.argv[1]
if not os.path.exists(filename):
    print (filename + ': no such file')
    sys.exit(2)
# get word list
with open (filename, "r") as file:
    words = file.read().replace('\n', ' ').strip().split()
for word in words:
    suggested_spelling = wikipedia.suggest(word)
    if suggested_spelling is not None:
        try:
            page = wikipedia.page(suggested_spelling)
        except wikipedia.exceptions.DisambiguationError:
            print('[^'+word+']: '+suggested_spelling)
        else:
            print('['+word+']: '+page.url)